TLC calculation
fraunhofer-iem/software-product-health-analyzer pull request #17
Opened 2024-08-30 13:39 UTC by janniclas

2024-08-30 14:00 UTC, AnakinRaW requested changes

2024-08-30 14:00 UTC, AnakinRaW commented on adapter/src/main/kotlin/de/fraunhofer/iem/kpiCalculator/adapter/tools/tlc/model/TechnicalLag.kt
> +    val releaseDistance: Triple<Int, Int, Int>,
maybe convert triple to own class.

2024-08-30 14:00 UTC, AnakinRaW commented on adapter/src/main/kotlin/de/fraunhofer/iem/kpiCalculator/adapter/tools/tlc/util/TimeHelper.kt
> +object TimeHelper {
internal ?

2024-08-30 14:00 UTC, AnakinRaW commented on adapter/src/main/kotlin/de/fraunhofer/iem/kpiCalculator/adapter/tools/tlc/model/Artifact.kt
> +                versionNumber = validateAndHarmonizeVersionString(versionNumber)
what about 4.0.0.0 ? In some ecosystems, while not recommened, it's allowed

2024-08-30 14:00 UTC, AnakinRaW commented on adapter/src/main/kotlin/de/fraunhofer/iem/kpiCalculator/adapter/tools/tlc/TlcAdapter.kt
> +            return TechLagResult.Incomplete(
why is this incomplete? Isn't it "allowed" if something does not have dependencies? Core runtime libraries usually have this.

2024-08-30 14:00 UTC, AnakinRaW commented on adapter/src/main/kotlin/de/fraunhofer/iem/kpiCalculator/adapter/tools/tlc/TlcAdapter.kt
> +        val currentVersion = artifact.versions.find { it.versionNumber == node.usedVersion }
i think, `latestVersion` is a better name. current and target may be understood as the same thing.

2024-08-30 14:00 UTC, AnakinRaW commented on adapter/src/main/kotlin/de/fraunhofer/iem/kpiCalculator/adapter/tools/tlc/TlcAdapter.kt
> +    private fun getTargetVersion(
make internal and test independently

2024-09-02 06:28 UTC, janniclas commented on adapter/src/main/kotlin/de/fraunhofer/iem/kpiCalculator/adapter/tools/tlc/TlcAdapter.kt
> +        val currentVersion = artifact.versions.find { it.versionNumber == node.usedVersion }
I understand the confusion. However, it's not necessarily the latest. target is depending on `targetUpdateType`, which tells us if we try to update to a major, minor or patch release. But `currentVersion` is what we found in the project, so maybe `usedVersion` would be a better name and also help?

2024-09-02 06:31 UTC, janniclas commented on adapter/src/main/kotlin/de/fraunhofer/iem/kpiCalculator/adapter/tools/tlc/TlcAdapter.kt
> +            return TechLagResult.Incomplete(
forgot to change the naming. Will change to `Empty`

2024-09-02 06:57 UTC, janniclas commented on adapter/src/main/kotlin/de/fraunhofer/iem/kpiCalculator/adapter/tools/tlc/model/Artifact.kt
> +                versionNumber = validateAndHarmonizeVersionString(versionNumber)
// Version parsing pattern: 1.2.3-alpha+build
    internal const val VERSION_REGEX: String = "^$CORE_VERSION$PRE_RELEASE?$BUILD?\$"

    // Prefixed version parsing pattern: v1.2-alpha+build
    internal const val LOOSE_VERSION_REGEX: String = "^v?$LOOSE_CORE_VERSION$PRE_RELEASE?$BUILD?\$"

the regex from the semver library we use (and the semver standard) doesn't allow that and will fail with an invalid version exception (which we should probably catch so we don't crash due to one library with weired format)

2024-09-02 09:38 UTC, merged